name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: lint
    strategy:
      matrix:
        go: ["1.21"]
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m

      - uses: bufbuild/buf-setup-action@v1
        with:
          version: "latest"
      - uses: bufbuild/buf-lint-action@v1

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.21"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Run coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic

      - name: Bench
        run: go test -bench=. ./...
